import type { Metadata } from 'next';
import { Montserrat, Plus_Jakarta_Sans, Poppins } from 'next/font/google';
import './normalize.css';
import './globals.css';

const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['500', '600'],
	variable: '--font-montserrat',
	display: 'swap',
});
const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500'],
	variable: '--font-poppins',
	display: 'swap',
});

const plusJakartaSans = Plus_Jakarta_Sans({
	subsets: ['latin'],
	weight: ['400', '500'],
	variable: '--font-plus-jakarta-sans',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Services | Template',
	description: 'Generated by create next app',
	keywords: ['service'],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable} ${plusJakartaSans.variable} ${poppins.variable}`}>{children}</body>
		</html>
	);
}
